version: "3.9"
services:
  db:
    image: postgres:16
    container_name: postgres-stock
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: stock
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
