# src/main/resources/application.yml
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stock
    username: tu_usuario
    password: tu_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      indent_output: true
server:
  port: 8080
