# .github/workflows/build-backend.yml
name: Build & Test Backend

on:
  push:
    paths:
      - 'stock-backend/**'
  pull_request:
    paths:
      - 'stock-backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn -B clean install --file stock-backend/pom.xml
